// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqmA0sOYXtlX5ycSZ9OB-LOYZXavMcX-U',
    appId: '1:46658532627:web:11ba08ee9f1def9959d6e6',
    messagingSenderId: '46658532627',
    projectId: 'iism2024',
    authDomain: 'iism2024.firebaseapp.com',
    storageBucket: 'iism2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW7Wf2OdKIZKIW7U74I0AQI1tNt8BSlqA',
    appId: '1:46658532627:android:d98cf727496d05ea59d6e6',
    messagingSenderId: '46658532627',
    projectId: 'iism2024',
    storageBucket: 'iism2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWfk2iZlvQyxSM2LcohK8FhLw9FoqaqHM',
    appId: '1:46658532627:ios:c899710f2b28a6e859d6e6',
    messagingSenderId: '46658532627',
    projectId: 'iism2024',
    storageBucket: 'iism2024.appspot.com',
    iosBundleId: 'com.example.iism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWfk2iZlvQyxSM2LcohK8FhLw9FoqaqHM',
    appId: '1:46658532627:ios:c899710f2b28a6e859d6e6',
    messagingSenderId: '46658532627',
    projectId: 'iism2024',
    storageBucket: 'iism2024.appspot.com',
    iosBundleId: 'com.example.iism',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqmA0sOYXtlX5ycSZ9OB-LOYZXavMcX-U',
    appId: '1:46658532627:web:546090c54859006059d6e6',
    messagingSenderId: '46658532627',
    projectId: 'iism2024',
    authDomain: 'iism2024.firebaseapp.com',
    storageBucket: 'iism2024.appspot.com',
  );
}
